### ISSUE TITLE
[ERROR] Command "delete" not found

### ISSUE THREAD

**Issue by entrptaher** [postgres-ai/database-lab-engine#159]
From the UI, I cannot delete a snapshot.

![image](https://user-images.githubusercontent.com/8284972/220642345-2ac07551-3cd7-44ed-913e-9ebaa1cbf32c.png)

From the CLI,

```
dblab snapshot delete dblab_pool/dataset_2@snapshot_20230110074634

[ERROR] Command "delete" not found
```

Here is the dblab version,
```
dblab version v3.3.0-20221222-1957
```

**Comment by NikolayS** [comment]
@entrptaher thanks for the bug report!

It seems, you've got the latest UI version, from DLE 4.0 branch which is currently [under development](https://gitlab.com/postgres-ai/database-lab/-/tree/dle-4-0) (and where snapshot management via API/CLI/UI is already implemented). While backend is 3.3.0.

Our bad – I guess it's because we rely on the `:latest` tag for the UI docker image being used. We've fixed it. Please pull the UI image again and restart DLE:

```bash
sudo docker pull postgresai/ce-ui:latest
sudo docker stop dblab_server
sudo docker start dblab_server
```

Let me know if you still have questions!

(And, if you're interested in beta-testing DLE 4.0 – with snapshot management and full-featured DB branching – contact me at nik@postgres.ai)
